version: '3.9'

services:
  pgadmin4:
    image: dpage/pgadmin4:8.14.0
    container_name: pgadmin4_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: daniel123
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/lib/pgadmin
    networks:
      - pruebatecnica_network

  postgres:
    image: postgres:13.18
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: postgres
    networks:
      - pruebatecnica_network
    ports:
      - "5432:5432"
    volumes:
      - pruebatecnica-volume:/var/lib/postgresql/data

networks:
  pruebatecnica_network:
    external: true
volumes:
  pruebatecnica-volume: